#!/bin/sh
# cccc installer — puts the `cccc` command (the TUI + statusline + the local
# `claudectl` MCP/plugin) on your PATH. cccc operates the Claude Max accounts
# behind the llm.hostbun.cc router and steers the terminals that burn them.
#
# This tool lives in the `cccc/` subdir of the llm-hostbun-router repo (it used to
# be its own `claudectl` repo). The cmux Dock split off into the claudectl repo and
# ships its own installer (cmuxdock/cccl) — this one does NOT install those.
#
# Run it either way:
#   • from a clone:   sh cccc/install.sh
#   • standalone:     pipe it and it clones llm-hostbun-router for you.
#
# Env knobs:
#   PREFIX=$HOME/.local/bin        where to put the wrappers
#   CCCC_DIR=$HOME/.llm-hostbun-router  clone location when bootstrapping
#   NO_MODIFY_PATH=1               don't touch your shell rc
set -eu

REPO_SSH="git@github.com:devdashco/llm-hostbun-router.git"
REPO_HTTPS="https://github.com/devdashco/llm-hostbun-router.git"
CCCC_DIR="${CCCC_DIR:-$HOME/.llm-hostbun-router}"
PREFIX="${PREFIX:-$HOME/.local/bin}"

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- 0. the only runtime dependency ----------------------------------------
command -v python3 >/dev/null 2>&1 || die "python3 not found — install Python 3 first"

# --- 1. locate the source: this clone's cccc/, or bootstrap one ------------
DIR="$(cd "$(dirname "$0")" 2>/dev/null && pwd || echo "$PWD")"
if [ ! -f "$DIR/tui/claudectl_tui.py" ]; then
  command -v git >/dev/null 2>&1 || die "git not found"
  if [ -d "$CCCC_DIR/.git" ]; then
    say "updating existing clone at $CCCC_DIR"
    git -C "$CCCC_DIR" pull --ff-only || say "warn: pull failed — using existing clone"
  else
    say "cloning llm-hostbun-router -> $CCCC_DIR"
    git clone "$REPO_SSH" "$CCCC_DIR" 2>/dev/null \
      || gh repo clone devdashco/llm-hostbun-router "$CCCC_DIR" 2>/dev/null \
      || git clone "$REPO_HTTPS" "$CCCC_DIR" \
      || die "clone failed — need GitHub access (SSH key, 'gh auth login', or HTTPS token)"
  fi
  DIR="$CCCC_DIR/cccc"
fi

# --- 2. install the `cccc` command + its subcommands -----------------------
mkdir -p "$PREFIX"
chmod +x "$DIR/tui/claudectl_tui.py" "$DIR/tui/cccc_menu.py" "$DIR/tui/cccc_sync.py" "$DIR/tui/cccc_gateway.py" "$DIR/tui/panes_tui.py" "$DIR/tui/panes_gum.sh" \
  "$DIR/plugins/claudectl/mcp/ccc_refresh.py" "$DIR/plugins/claudectl/mcp/ccc_doctor.py" \
  "$DIR/plugins/claudectl/mcp/ccc_terminals_mcp.py" "$DIR/plugins/claudectl/mcp/ccc_restart_mcp.py"
command -v gum >/dev/null 2>&1 || say "tip: 'brew install gum' for the glam \`cccc panes\` picker (curses fallback works without it)"

# One-word WRAPPER SCRIPTS on PATH (not symlinks): each names its subcommand
# outright, so `cat $(command -v cccp)` shows exactly what runs. The Dock's
# non-interactive shell has no aliases, so a real command on PATH is required.
_wrapper() {  # _wrapper <name> <subcommand...>
  _n="$1"; shift
  rm -f "$PREFIX/$_n"            # rm FIRST: `>` onto a stale symlink writes THROUGH it
  { printf '#!/bin/sh\n'
    printf '# cccc — generated by cccc/install.sh. Edits will be overwritten.\n'
    printf '# Runs: cccc %s\n' "$*"
    printf 'exec python3 "%s/tui/claudectl_tui.py" %s "$@"\n' "$DIR" "$*"
  } > "$PREFIX/$_n"
  chmod +x "$PREFIX/$_n"
}
# cccc (bare) -> Textual chooser: pick claudectl (accounts) or localtools
rm -f "$PREFIX/cccc"
{ printf '#!/bin/sh\n'
  printf '# cccc — generated by cccc/install.sh. Edits will be overwritten.\n'
  printf '# Runs: cccc chooser (claudectl | localtools)\n'
  printf 'exec python3 "%s/tui/cccc_menu.py" "$@"\n' "$DIR"
} > "$PREFIX/cccc"
chmod +x "$PREFIX/cccc"
_wrapper cccp     panes
_wrapper cccd     doctor
_wrapper cccr     refresh
_wrapper cccs     sync
# NOTE: cmuxdock/cccl (the cmux Dock) now ship from the claudectl repo's own
# installer — this tool no longer generates them.

# Ensure $PREFIX is on PATH for EVERY shell (Dock shells skip .zshrc).
_ZENV="$HOME/.zshenv"
_on_path() {
  command -v zsh >/dev/null 2>&1 || return 1
  env -i HOME="$HOME" zsh -c "case \":\$PATH:\" in *\":$PREFIX:\"*) exit 0 ;; esac; exit 1"
}
if _on_path; then
  :
elif grep -qF "$PREFIX" "$_ZENV" 2>/dev/null; then
  :
else
  printf '\ncase ":$PATH:" in *":%s:"*) ;; *) export PATH="%s:$PATH" ;; esac\n' "$PREFIX" "$PREFIX" >> "$_ZENV"
  say "added $PREFIX to PATH in ~/.zshenv"
fi
say "installed: cccc + cccp/cccd/cccr/cccs -> $PREFIX (wrappers)  [from $DIR]"

# --- machine name: STABLE per-box id (fleet name AND the consumer id for routing) ---
MACHINE_FILE="$HOME/.claude-accounts/.cccc-machine"
if [ ! -s "$MACHINE_FILE" ]; then
  mkdir -p "$HOME/.claude-accounts"
  MN="${CLAUDECTL_MACHINE:-$(hostname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-' | cut -c1-24)}"
  [ -z "$MN" ] && MN="box"
  printf '%s' "$MN" > "$MACHINE_FILE"
  say "machine name set: '$MN'  (override: printf %s NAME > $MACHINE_FILE)"
fi

# --- 2a. the local `claudectl` MCP ships WITH THE PLUGIN -------------------
# The single local stdio MCP `claudectl` (mcp/claudectl_local.py via
# mcp/claudectl_launch.sh, ${CLAUDE_PLUGIN_ROOT}-relative) merges the account/limit/
# proxy tools (server/, httpx -> llm.hostbun.cc) with terminals + plugin/mcp mgmt.
# Needs mcp+httpx for the account half; installs best-effort, else degrades to
# terminals-only. Any box that installs the plugin gets it — no per-machine add.
if command -v python3 >/dev/null 2>&1; then
  if ! python3 -c 'import mcp, httpx' >/dev/null 2>&1; then
    python3 -m pip install --user --quiet mcp httpx >/dev/null 2>&1 \
      || python3 -m pip install --user --quiet --break-system-packages mcp httpx >/dev/null 2>&1 \
      || true
    if python3 -c 'import mcp, httpx' >/dev/null 2>&1; then
      say "installed mcp+httpx — claudectl MCP serves the full account+terminals SDK"
    else
      say "note: couldn't install mcp+httpx — claudectl MCP serves terminals-only until deps exist"
    fi
  fi
fi
# Remove stale user-scope registrations from before the merge.
if [ "${CLAUDECTL_NO_MCP_CLEANUP:-0}" != "1" ] && command -v claude >/dev/null 2>&1; then
  for m in ccc-terminals ccc-pane ccc-restart ccc-lsp ccc-plugin; do
    claude mcp remove "$m" -s user >/dev/null 2>&1 || true
  done
fi
# Fallback for a bare clone WITHOUT the plugin installed: register at user scope.
if command -v claude >/dev/null 2>&1 && ! claude plugin list 2>/dev/null | grep -q "claudectl"; then
  claude mcp remove claudectl -s user >/dev/null 2>&1 || true
  claude mcp add claudectl -s user -- sh "$DIR/plugins/claudectl/mcp/claudectl_launch.sh" >/dev/null 2>&1 || true
  say "no claudectl plugin found — registered the merged claudectl MCP at user scope (fallback)"
fi

# --- 2b. install the statusline + register it globally ---------------------
if [ "${CLAUDECTL_NO_STATUSLINE:-0}" != "1" ] && [ -f "$DIR/statusline/cccc-statusline.py" ]; then
  chmod +x "$DIR/statusline/cccc-statusline.py"
  SL_CMD="python3 $DIR/statusline/cccc-statusline.py"
  CLAUDECTL_SL_CMD="$SL_CMD" python3 - "$HOME/.claude/settings.json" <<'PY' && \
    say "statusline registered -> ~/.claude/settings.json  (same line in every pane)" || true
import json, os, sys
path = sys.argv[1]
cmd = os.environ["CLAUDECTL_SL_CMD"]
os.makedirs(os.path.dirname(path), exist_ok=True)
try:
    with open(path) as f:
        cfg = json.load(f)
except (OSError, json.JSONDecodeError):
    cfg = {}
cur = cfg.get("statusLine")
cur_cmd = cur.get("command") if isinstance(cur, dict) else None
OURS = ("cccc-statusline.py", "statusline-ratelimits.sh")
if cur_cmd and not any(k in cur_cmd for k in OURS):
    print(f"  note: keeping your existing statusLine ({cur_cmd!r})", file=sys.stderr)
    sys.exit(1)
cfg["statusLine"] = {"type": "command", "command": cmd}
with open(path, "w") as f:
    json.dump(cfg, f, indent=2)
PY
  true
fi

# --- 2b. fast mode HARD OFF (durable across reinstalls / new boxes) --------
python3 - "$HOME/.claude/settings.json" <<'PY' && say "fast mode locked OFF (CLAUDE_CODE_DISABLE_FAST_MODE=1)" || true
import json, os, sys
path = sys.argv[1]
os.makedirs(os.path.dirname(path), exist_ok=True)
try:
    with open(path) as f: cfg = json.load(f)
except (OSError, json.JSONDecodeError): cfg = {}
env = cfg.get("env")
if not isinstance(env, dict): env = {}; cfg["env"] = env
changed = False
if env.get("CLAUDE_CODE_DISABLE_FAST_MODE") != "1":
    env["CLAUDE_CODE_DISABLE_FAST_MODE"] = "1"; changed = True
if cfg.pop("fastMode", None) is not None: changed = True
if changed:
    with open(path, "w") as f: json.dump(cfg, f, indent=2)
else:
    sys.exit(0)
PY
true

# --- 2b'. gateway FAIL-OPEN routing (dynamic base URL; direct keychain fallback) ---
# Moves the gateway identity OUT of the static settings.json env — which OVERRIDES the
# shell and is plain JSON, so it can never fail over — and INTO the files the fail-open
# resolver (shell/gateway-route.sh) reads. Result: router up → route through it; router
# down → UNSET the gateway env → `claude` talks to api.anthropic.com on the keychain
# OAuth login (never breaks). The statusline flags the fallback loudly.
#
# OPT-IN (CLAUDECTL_GATEWAY_ROUTE=1) on purpose: it depends on the box SOURCING its shell
# rc before launching claude. Interactive dev boxes do; a daemon that execs claude from a
# launcher that skips rc would fall to direct and MISBILL. So we don't flip it fleet-wide —
# enable it per box (deploy.sh can pass it) once you've confirmed rc is sourced there.
if [ "${CLAUDECTL_GATEWAY_ROUTE:-0}" = "1" ] && [ -f "$DIR/shell/gateway-route.sh" ]; then
  python3 - "$HOME/.claude/settings.json" "$HOME/.claude-accounts" <<'PY' && say "gateway identity migrated out of settings.json env (fail-open ready)" || true
import json, os, sys
path, acctdir = sys.argv[1], sys.argv[2]
try:
    with open(path) as f: cfg = json.load(f)
except (OSError, json.JSONDecodeError): cfg = {}
env = cfg.get("env")
if not isinstance(env, dict): sys.exit(1)
os.makedirs(acctdir, exist_ok=True)
tok = env.get("ANTHROPIC_AUTH_TOKEN")
if isinstance(tok, str) and tok.startswith("sk-llm-"):        # our router key → key file (0600)
    kp = os.path.join(acctdir, ".cccc-key")
    with open(kp, "w") as f: f.write(tok.strip())
    os.chmod(kp, 0o600)
for ln in (env.get("ANTHROPIC_CUSTOM_HEADERS") or "").splitlines():   # X-Consumer → machine id
    if ln.lower().startswith("x-consumer:"):
        name = ln.split(":", 1)[1].strip()
        mp = os.path.join(acctdir, ".cccc-machine")
        cur = open(mp).read().strip() if os.path.exists(mp) else ""
        if name and not cur:
            with open(mp, "w") as f: f.write(name)
changed = False
for k in ("ANTHROPIC_BASE_URL", "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_CUSTOM_HEADERS"):
    if k in env: del env[k]; changed = True                # the resolver owns these now
if changed:
    with open(path, "w") as f: json.dump(cfg, f, indent=2)
else:
    sys.exit(1)
PY
  true
  RESOLVER="$DIR/shell/gateway-route.sh"; RMARK="# cccc gateway fail-open route"
  _rcs="$HOME/.zshenv"; [ "$(uname 2>/dev/null)" = Linux ] && _rcs="$_rcs $HOME/.bashrc"
  for rc in $_rcs; do
    if ! grep -qF "$RMARK" "$rc" 2>/dev/null; then
      printf '\n[ -f "%s" ] && . "%s"  %s\n' "$RESOLVER" "$RESOLVER" "$RMARK" >> "$rc"
      say "sourced gateway fail-open resolver in $rc"
    fi
  done
fi

# --- 2c. strip ALL retired claudectl crons (no background sync/switch) -----
if command -v crontab >/dev/null 2>&1; then
  CUR="$(crontab -l 2>/dev/null || true)"
  if printf '%s\n' "$CUR" | grep -qE 'cccc (sync|autoswitch)|# claudectl auto-(sync|switch)'; then
    printf '%s\n' "$CUR" \
      | grep -vE '# claudectl auto-(sync|switch)' \
      | grep -vE 'cccc(-| )(sync|autoswitch)( --quiet)?' \
      | crontab - && say "removed retired claudectl crons (pull manually)"
  fi
fi

# --- 2d. share plugins into alternate account config dirs ------------------
# `claude-philip` / `-william` / `-emphyx` (zsh aliases) launch with a per-account
# CLAUDE_CONFIG_DIR=$HOME/.claude-<name>. Those dirs hold only .credentials.json —
# NO plugin store, NO enabledPlugins — so a switched-account launch loads ZERO
# plugins. cccc's own token-swap stays on ~/.claude and is unaffected; this heals
# the alias dirs by symlinking the machine-global plugin store + settings into
# each (their own .credentials.json keeps the account identity separate).
# Idempotent — reconverges on every install/sync.
for acct in "$HOME"/.claude-*; do
  [ -d "$acct" ] || continue
  case "$acct" in "$HOME/.claude-accounts") continue ;; esac   # token store, not a config dir
  for item in plugins settings.json; do
    src="$HOME/.claude/$item"; dst="$acct/$item"
    [ -e "$src" ] || continue
    [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ] && continue   # already linked
    rm -rf "$dst"; ln -s "$src" "$dst" \
      && say "linked $(basename "$acct")/$item -> ~/.claude/$item"
  done
done

# --- 3. make sure PREFIX is on PATH ----------------------------------------
case ":$PATH:" in
  *":$PREFIX:"*) : ;;
  *)
    if [ "${NO_MODIFY_PATH:-0}" = "1" ]; then
      say "NOTE: add $PREFIX to your PATH to run cccc"
    else
      rc="$HOME/.profile"
      case "${SHELL:-}" in
        *zsh)  rc="$HOME/.zshrc" ;;
        *bash) rc="$HOME/.bashrc" ;;
      esac
      line="export PATH=\"$PREFIX:\$PATH\""
      if ! grep -qsF "$line" "$rc" 2>/dev/null; then
        printf '\n# added by cccc installer\n%s\n' "$line" >> "$rc"
        say "added $PREFIX to PATH in $rc"
      fi
      say "-> run 'source $rc' or open a new terminal so cccc is found"
    fi
    ;;
esac

# --- 3b. VERIFY — never report success on a broken install ------------------
# Every claim above is re-checked from the OUTSIDE: what kind of claude install
# this box has, that settings.json really points at THIS checkout's statusline,
# and that the statusline actually executes. A failed check fails the installer
# (nonzero exit), which `cccc sync` logs loudly instead of "install.sh refreshed".
say ""
say "verifying install…"
CLAUDECTL_DIR="$DIR" python3 - "$HOME/.claude/settings.json" <<'PY'
import json, os, subprocess, sys
path, DIR = sys.argv[1], os.environ["CLAUDECTL_DIR"]
fails, notes = [], []

# what kind of claude installation is this box running? (report before touching)
claude = subprocess.run(["sh", "-c", "command -v claude"], capture_output=True, text=True).stdout.strip()
ver = ""
if claude:
    ver = subprocess.run([claude, "--version"], capture_output=True, text=True, timeout=20).stdout.strip()[:40]
kind = "none"
if claude:
    kind = "native" if ".local" in claude or "/usr/local" in claude else "npm/other"
    if "/plugins/" in os.path.realpath(claude):
        kind = "plugin-shim"
login = "keychain (macOS)" if sys.platform == "darwin" else (
    "~/.claude/.credentials.json" if os.path.exists(os.path.expanduser("~/.claude/.credentials.json")) else "none found")
notes.append(f"claude install: {kind}" + (f" · {ver}" if ver else " · NOT ON PATH") + f" · login: {login}")
notes.append(f"settings file:  {path}")

# settings.json must parse — a half-written file bricks every claude launch
try:
    cfg = json.load(open(path))
except FileNotFoundError:
    cfg, _ = {}, fails.append(f"{path} does not exist — nothing was registered")
except json.JSONDecodeError as e:
    cfg, _ = {}, fails.append(f"{path} is INVALID JSON ({e}) — claude will ignore all of it")

# statusline: must be OURS and must point at THIS checkout (a stale path from a
# previous clone renders an old line forever and looks exactly like 'installed')
want = f"{DIR}/statusline/cccc-statusline.py"
sl = (cfg.get("statusLine") or {}).get("command", "")
if os.environ.get("CLAUDECTL_NO_STATUSLINE") == "1":
    notes.append("statusline:     skipped (CLAUDECTL_NO_STATUSLINE=1)")
elif "cccc-statusline.py" not in sl and "statusline-ratelimits.sh" not in sl and sl:
    notes.append(f"statusline:     foreign, deliberately kept ({sl[:60]!r})")
elif want not in sl:
    fails.append(f"statusLine points at {sl or '(nothing)'!r}, expected {want!r} — stale checkout path?")
else:
    # it must also RUN: registration that crashes on stdin is a blank line in every pane
    r = subprocess.run(["python3", want], input='{"workspace":{"current_dir":"/tmp"},"model":{"display_name":"v"}}',
                       capture_output=True, text=True, timeout=30)
    if r.returncode != 0 or not r.stdout.strip():
        fails.append(f"statusline registered but does not execute: rc={r.returncode} {r.stderr.strip()[:120]!r}")
    else:
        notes.append("statusline:     ✓ registered to this checkout and renders")

# fast-mode lock really landed
if ((cfg.get("env") or {}).get("CLAUDE_CODE_DISABLE_FAST_MODE")) != "1":
    fails.append("env.CLAUDE_CODE_DISABLE_FAST_MODE is not '1' — fast-mode lock did not land")

# wrappers resolve on a fresh shell's PATH
w = subprocess.run(["sh", "-lc", "command -v cccc"], capture_output=True, text=True).stdout.strip()
if not w:
    fails.append("`cccc` not on PATH in a login shell — wrapper or PATH line missing")
else:
    notes.append(f"cccc on PATH:   ✓ {w}")

for n in notes:
    print(f"  {n}")
for f in fails:
    print(f"  ✗ {f}", file=sys.stderr)
sys.exit(1 if fails else 0)
PY
VERIFY_RC=$?
if [ "$VERIFY_RC" != "0" ]; then
  say ""
  say "✗ INSTALL VERIFICATION FAILED — the checks above name what is wrong. Fix and re-run."
  exit 1
fi
say "✓ verified"

# --- 4. done ---------------------------------------------------------------
say ""
say "run:     cccc"
case "$DIR" in
  */.claude/plugins/*) say "update:  /plugin marketplace update claudectl" ;;
  *)                   say "update:  git -C $(dirname "$DIR") pull   (or re-run this installer)" ;;
esac
